USE [GD2C2020]
GO

-- ********** SCHEMA CREATION **********

IF(NOT EXISTS(SELECT * FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'EL_KUELGUE'))
  BEGIN
      exec ('CREATE SCHEMA[EL_KUELGUE]');
      print 'esquema creado';
    END

-- ********** TABLES CREATION **********

-- CLIENTE
IF OBJECT_ID ('EL_KUELGUE.CLIENTE', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.CLIENTE; 
GO

CREATE TABLE EL_KUELGUE.CLIENTE (
    [CLIENTE_CODIGO] INT IDENTITY(1, 1) PRIMARY KEY,
    [CLIENTE_APELLIDO] [nvarchar](255) NOT NULL,
    [CLIENTE_NOMBRE] [nvarchar](255) NOT NULL,
	[CLIENTE_DIRECCION] [nvarchar](255) NOT NULL,
	[CLIENTE_DNI] [decimal](18, 0) NOT NULL,
	[CLIENTE_FECHA_NAC] [datetime2](3) NOT NULL,
	[CLIENTE_MAIL] [nvarchar](255) NOT NULL
)

-- SUCURSAL
IF OBJECT_ID ('EL_KUELGUE.SUCURSAL', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.SUCURSAL; 
GO

CREATE TABLE EL_KUELGUE.SUCURSAL (
    [SUCURSAL_CODIGO] SMALLINT IDENTITY(1, 1) PRIMARY KEY,
    [SUCURSAL_DIRECCION] [nvarchar](255) NOT NULL,
	[SUCURSAL_MAIL] [nvarchar](255) NOT NULL,
	[SUCURSAL_TELEFONO] [decimal](18, 0) NOT NULL,
	[SUCURSAL_CIUDAD] [nvarchar](255) NOT NULL
)

-- FABRICANTE
IF OBJECT_ID ('EL_KUELGUE.FABRICANTE', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.FABRICANTE; 
GO

CREATE TABLE EL_KUELGUE.FABRICANTE (
    [FABRICANTE_CODIGO] INT IDENTITY(1, 1) PRIMARY KEY,
	[FABRICANTE_NOMBRE] [nvarchar](255) NOT NULL
)

-- MODELO
IF OBJECT_ID ('EL_KUELGUE.MODELO', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.MODELO; 
GO

CREATE TABLE EL_KUELGUE.MODELO (
    [MODELO_CODIGO] [decimal](18, 0) PRIMARY KEY,
    [MODELO_NOMBRE] [nvarchar](255) NOT NULL,
	[MODELO_POTENCIA] [decimal](18, 0) NOT NULL,
	[FABRICANTE_CODIGO] [int] NOT NULL
)

-- TRANSMISION
IF OBJECT_ID ('EL_KUELGUE.TRANSMISION', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.TRANSMISION; 
GO

CREATE TABLE EL_KUELGUE.TRANSMISION (
    [TIPO_TRANSMISION_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[TIPO_TRANSMISION_DESC] [nvarchar](255) NOT NULL
)

-- CAJA
IF OBJECT_ID ('EL_KUELGUE.CAJA', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.CAJA; 
GO

CREATE TABLE EL_KUELGUE.CAJA (
    [TIPO_CAJA_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[TIPO_CAJA_DESC] [nvarchar](255) NOT NULL
)

-- MOTOR
IF OBJECT_ID ('EL_KUELGUE.MOTOR', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.MOTOR; 
GO

CREATE TABLE EL_KUELGUE.MOTOR (
    [TIPO_MOTOR_CODIGO] [decimal](18, 0) PRIMARY KEY
)

-- TIPO_DE_AUTOMOVIL
IF OBJECT_ID ('EL_KUELGUE.TIPO_DE_AUTOMOVIL', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.TIPO_DE_AUTOMOVIL; 
GO

CREATE TABLE EL_KUELGUE.TIPO_DE_AUTOMOVIL (
    [TIPO_AUTO_CODIGO] [decimal](18, 0) PRIMARY KEY,
    [TIPO_AUTO_DESC] [nvarchar](255) NOT NULL
)

-- FICHA_TECNICA_DE_AUTOMOVIL
IF OBJECT_ID ('EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL', 'U') IS NOT NULL
	DROP TABLE EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL
GO

CREATE TABLE EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL (
	[FICHA_TECNICA_CODIGO] INT IDENTITY (1, 1) PRIMARY KEY,
	[AUTO_NRO_CHASIS] [nvarchar](50) NOT NULL,
	[AUTO_NRO_MOTOR] [nvarchar](50) NOT NULL,
	[TIPO_TRANSMISION_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_CAJA_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_MOTOR_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_AUTO_CODIGO] [decimal](18, 0) NOT NULL,
	[MODELO_CODIGO] [decimal](18, 0) NOT NULL
)

-- AUTOMOVIL
IF OBJECT_ID ('EL_KUELGUE.AUTOMOVIL', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.AUTOMOVIL; 
GO

CREATE TABLE EL_KUELGUE.AUTOMOVIL (
    [AUTO_CODIGO] INT IDENTITY(1, 1) PRIMARY KEY,
	[AUTO_PATENTE] [nvarchar](50) NOT NULL,
	[AUTO_FECHA_ALTA] [datetime2](3) NOT NULL,
	[AUTO_CANT_KMS] [decimal](18, 0) NOT NULL,
	[FICHA_TECNICA_CODIGO] [int]
)

-- AUTOPARTE
IF OBJECT_ID ('EL_KUELGUE.AUTOPARTE', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.AUTOPARTE; 
GO

CREATE TABLE EL_KUELGUE.AUTOPARTE (
    [AUTO_PARTE_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[AUTO_PARTE_DESCRIPCION] [nvarchar](255) NOT NULL,
	[MODELO_CODIGO] [decimal](18, 0) NOT NULL
)

-- COMPRA_DE_AUTOMOVIL
CREATE TABLE EL_KUELGUE.COMPRA_DE_AUTOMOVIL (
	[SUCURSAL_CODIGO] SMALLINT NOT NULL,
	[CLIENTE_CODIGO] INT NOT NULL,
	[]
)

-- ********** MIGRATION **********

-- CLIENTE
INSERT INTO EL_KUELGUE.CLIENTE
SELECT DISTINCT CLIENTE_APELLIDO, CLIENTE_NOMBRE, CLIENTE_DIRECCION, CLIENTE_DNI, CLIENTE_FECHA_NAC, CLIENTE_MAIL
FROM EL_KUELGUE.Maestra
WHERE CLIENTE_APELLIDO IS NOT NULL
UNION
SELECT DISTINCT FAC_CLIENTE_APELLIDO, FAC_CLIENTE_NOMBRE, FAC_CLIENTE_DIRECCION, FAC_CLIENTE_DNI, FAC_CLIENTE_FECHA_NAC, FAC_CLIENTE_MAIL
FROM EL_KUELGUE.Maestra
WHERE FAC_CLIENTE_APELLIDO IS NOT NULL
GO

-- SUCURSAL
-- Desprecio las sucursales FAC_SUCURSAL_* puesto a que son las mismas 7 que se obtienen con esta query
INSERT INTO EL_KUELGUE.SUCURSAL
SELECT DISTINCT SUCURSAL_DIRECCION, SUCURSAL_MAIL, SUCURSAL_TELEFONO, SUCURSAL_CIUDAD
FROM EL_KUELGUE.Maestra
WHERE SUCURSAL_CIUDAD IS NOT NULL
GO

-- FABRICANTE
INSERT INTO EL_KUELGUE.FABRICANTE
SELECT DISTINCT [FABRICANTE_NOMBRE]
FROM EL_KUELGUE.Maestra
WHERE [FABRICANTE_NOMBRE] IS NOT NULL
GO

-- MODELO
INSERT INTO EL_KUELGUE.MODELO
SELECT DISTINCT MODELO_CODIGO, MODELO_NOMBRE, MODELO_POTENCIA, FABRICANTE_CODIGO
FROM EL_KUELGUE.Maestra m JOIN EL_KUELGUE.FABRICANTE f ON f.FABRICANTE_NOMBRE = m.FABRICANTE_NOMBRE 
WHERE[MODELO_CODIGO] IS NOT NULL
GO

-- TRANSMISIÓN
INSERT INTO EL_KUELGUE.TRANSMISION
SELECT DISTINCT TIPO_TRANSMISION_CODIGO, TIPO_TRANSMISION_DESC
FROM EL_KUELGUE.Maestra
WHERE TIPO_TRANSMISION_CODIGO IS NOT NULL
GO

-- CAJA
INSERT INTO EL_KUELGUE.CAJA
SELECT DISTINCT TIPO_CAJA_CODIGO, TIPO_CAJA_DESC
FROM EL_KUELGUE.Maestra
WHERE TIPO_CAJA_CODIGO IS NOT NULL
GO

-- MOTOR
INSERT INTO EL_KUELGUE.MOTOR
SELECT DISTINCT TIPO_MOTOR_CODIGO
FROM EL_KUELGUE.Maestra
WHERE TIPO_MOTOR_CODIGO IS NOT NULL
GO

-- TIPO_DE_AUTOMOVIL
INSERT INTO EL_KUELGUE.TIPO_DE_AUTOMOVIL
SELECT DISTINCT TIPO_AUTO_CODIGO, TIPO_AUTO_DESC
FROM EL_KUELGUE.Maestra
WHERE TIPO_AUTO_CODIGO IS NOT NULL
GO

-- FICHA_TECNICA_DE_AUTOMOVIL
INSERT INTO EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL
SELECT DISTINCT AUTO_NRO_CHASIS, AUTO_NRO_MOTOR, TIPO_TRANSMISION_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, TIPO_AUTO_CODIGO, MODELO_CODIGO
FROM EL_KUELGUE.Maestra
WHERE AUTO_NRO_CHASIS IS NOT NULL
GO

-- AUTOMOVIL
INSERT INTO gd_esquema.AUTOMOVIL
SELECT DISTINCT AUTO_PATENTE, AUTO_FECHA_ALTA, AUTO_CANT_KMS, FICHA_TECNICA_CODIGO
FROM gd_esquema.Maestra m JOIN gd_esquema.FICHA_TECNICA_DE_AUTOMOVIL f ON f.MODELO_CODIGO = m.MODELO_CODIGO
WHERE AUTO_PATENTE IS NOT NULL
GO

-- AUTOPARTE
INSERT INTO EL_KUELGUE.AUTOPARTE
SELECT DISTINCT AUTO_PARTE_CODIGO, AUTO_PARTE_DESCRIPCION, MODELO_CODIGO
FROM EL_KUELGUE.Maestra
WHERE AUTO_PARTE_CODIGO IS NOT NULL
GO

-- ********** CONSTRAINS CREATION **********

ALTER TABLE EL_KUELGUE.MODELO
ADD FOREIGN KEY ([FABRICANTE_CODIGO]) REFERENCES EL_KUELGUE.FABRICANTE([FABRICANTE_CODIGO])
GO

ALTER TABLE EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL
ADD FOREIGN KEY ([TIPO_TRANSMISION_CODIGO]) REFERENCES EL_KUELGUE.TRANSMISION([TIPO_TRANSMISION_CODIGO])
GO

ALTER TABLE EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL
ADD FOREIGN KEY ([TIPO_CAJA_CODIGO]) REFERENCES EL_KUELGUE.CAJA([TIPO_CAJA_CODIGO])
GO

ALTER TABLE EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL
ADD FOREIGN KEY ([TIPO_MOTOR_CODIGO]) REFERENCES EL_KUELGUE.MOTOR([TIPO_MOTOR_CODIGO])
GO

ALTER TABLE EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL
ADD FOREIGN KEY ([TIPO_AUTO_CODIGO]) REFERENCES EL_KUELGUE.TIPO_DE_AUTOMOVIL([TIPO_AUTO_CODIGO])
GO

ALTER TABLE EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL
ADD FOREIGN KEY ([MODELO_CODIGO]) REFERENCES EL_KUELGUE.MODELO([MODELO_CODIGO])
GO

ALTER TABLE EL_KUELGUE.AUTOMOVIL
ADD FOREIGN KEY ([FICHA_TECNICA_CODIGO]) REFERENCES EL_KUELGUE.FICHA_TECNICA_DE_AUTOMOVIL([FICHA_TECNICA_CODIGO])
GO

ALTER TABLE EL_KUELGUE.AUTOPARTE
ADD FOREIGN KEY ([MODELO_CODIGO]) REFERENCES EL_KUELGUE.MODELO([MODELO_CODIGO])
GO
