USE GD2C2020
GO

IF OBJECT_ID ('EL_KUELGUE.DETALLE_FACTURA_AUTO_PARTE', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.DETALLE_FACTURA_AUTO_PARTE
GO

IF OBJECT_ID ('EL_KUELGUE.FACTURA_AUTOMOVIL', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.FACTURA_AUTOMOVIL
GO

IF OBJECT_ID ('EL_KUELGUE.FACTURA', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.FACTURA
GO

IF OBJECT_ID ('EL_KUELGUE.DETALLE_COMPRA_AUTO_PARTE', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.DETALLE_COMPRA_AUTO_PARTE
GO

IF OBJECT_ID ('EL_KUELGUE.COMPRA_AUTOMOVIL', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.COMPRA_AUTOMOVIL
GO

IF OBJECT_ID ('EL_KUELGUE.COMPRA', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.COMPRA
GO

IF OBJECT_ID ('EL_KUELGUE.AUTO_PARTE', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.AUTO_PARTE
GO

IF OBJECT_ID ('EL_KUELGUE.AUTOMOVIL', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.AUTOMOVIL
GO

IF OBJECT_ID ('EL_KUELGUE.FICHA_TECNICA_AUTOMOVIL', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.FICHA_TECNICA_AUTOMOVIL
GO

IF OBJECT_ID ('EL_KUELGUE.TIPO_AUTOMOVIL', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.TIPO_AUTOMOVIL
GO

IF OBJECT_ID ('EL_KUELGUE.CAJA', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.CAJA
GO

IF OBJECT_ID ('EL_KUELGUE.MOTOR', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.MOTOR
GO

IF OBJECT_ID ('EL_KUELGUE.TRANSMISION', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.TRANSMISION
GO

IF OBJECT_ID ('EL_KUELGUE.MODELO', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.MODELO
GO

IF OBJECT_ID ('EL_KUELGUE.FABRICANTE', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.FABRICANTE
GO

IF OBJECT_ID ('EL_KUELGUE.SUCURSAL', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.SUCURSAL
GO

IF OBJECT_ID ('EL_KUELGUE.CLIENTE', 'U') IS NOT NULL  
	DROP TABLE EL_KUELGUE.CLIENTE
GO