INSERT INTO EL_KUELGUE.AUTOMOVIL
SELECT DISTINCT AUTO_PATENTE, AUTO_NRO_MOTOR, AUTO_NRO_CHASIS, AUTO_FECHA_ALTA, AUTO_CANT_KMS, FICHA_TECNICA_CODIGO
FROM gd_esquema.Maestra m JOIN EL_KUELGUE.FICHA_TECNICA_AUTOMOVIL f ON (m.MODELO_CODIGO = f.MODELO_CODIGO)
WHERE AUTO_PATENTE IS NOT NULL
GO