INSERT INTO EL_KUELGUE.COMPRA_AUTOMOVIL
SELECT DISTINCT COMPRA_NRO, AUTO_CODIGO
FROM gd_esquema.Maestra m JOIN EL_KUELGUE.AUTOMOVIL a ON (m.AUTO_NRO_CHASIS = a.AUTO_NRO_CHASIS)
WHERE COMPRA_NRO IS NOT NULL AND FACTURA_NRO IS NULL AND AUTO_PARTE_CODIGO IS NULL
GO