INSERT INTO EL_KUELGUE.DETALLE_FACTURA_AUTO_PARTE
SELECT DISTINCT FACTURA_NRO, AUTO_PARTE_CODIGO, SUM(CANT_FACTURADA), PRECIO_FACTURADO
FROM gd_esquema.Maestra
WHERE COMPRA_NRO IS NULL AND FACTURA_NRO IS NOT NULL AND AUTO_PARTE_CODIGO IS NOT NULL
GROUP BY FACTURA_NRO, AUTO_PARTE_CODIGO, COMPRA_PRECIO, PRECIO_FACTURADO
GO