INSERT INTO EL_KUELGUE.FICHA_TECNICA_AUTOMOVIL
SELECT DISTINCT TIPO_TRANSMISION_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, TIPO_AUTO_CODIGO, MODELO_CODIGO
FROM gd_esquema.Maestra
WHERE TIPO_TRANSMISION_CODIGO IS NOT NULL
GO