INSERT INTO EL_KUELGUE.DETALLE_COMPRA_AUTO_PARTE
SELECT DISTINCT COMPRA_NRO, AUTO_PARTE_CODIGO, SUM(COMPRA_CANT), COMPRA_PRECIO
FROM gd_esquema.Maestra
WHERE COMPRA_NRO IS NOT NULL AND FACTURA_NRO IS NULL AND AUTO_PARTE_CODIGO IS NOT NULL
GROUP BY COMPRA_NRO, AUTO_PARTE_CODIGO, COMPRA_PRECIO
GO