INSERT INTO EL_KUELGUE.COMPRA
SELECT DISTINCT COMPRA_NRO, COMPRA_FECHA, COMPRA_PRECIO, CLIENTE_CODIGO, SUCURSAL_CODIGO
FROM gd_esquema.Maestra m JOIN EL_KUELGUE.CLIENTE c ON (m.CLIENTE_APELLIDO = c.CLIENTE_APELLIDO AND m.CLIENTE_NOMBRE = c.CLIENTE_NOMBRE AND m.CLIENTE_DNI = c.CLIENTE_DNI)
                          JOIN EL_KUELGUE.SUCURSAL s ON (m.SUCURSAL_TELEFONO = s.SUCURSAL_TELEFONO)
WHERE COMPRA_NRO IS NOT NULL AND FACTURA_NRO IS NULL AND AUTO_PARTE_CODIGO IS NULL
UNION
SELECT DISTINCT COMPRA_NRO, COMPRA_FECHA, SUM(COMPRA_PRECIO) COMPRA_PRECIO, CLIENTE_CODIGO, SUCURSAL_CODIGO
FROM gd_esquema.Maestra m JOIN EL_KUELGUE.CLIENTE c ON (m.CLIENTE_APELLIDO = c.CLIENTE_APELLIDO AND m.CLIENTE_NOMBRE = c.CLIENTE_NOMBRE AND m.CLIENTE_DNI = c.CLIENTE_DNI)
                          JOIN EL_KUELGUE.SUCURSAL s ON (m.SUCURSAL_TELEFONO = s.SUCURSAL_TELEFONO)
WHERE COMPRA_NRO IS NOT NULL AND FACTURA_NRO IS NULL AND AUTO_PARTE_CODIGO IS NOT NULL
GROUP BY COMPRA_NRO, COMPRA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO
GO