INSERT INTO EL_KUELGUE.MODELO
SELECT DISTINCT MODELO_CODIGO, MODELO_NOMBRE, MODELO_POTENCIA, FABRICANTE_CODIGO
FROM gd_esquema.Maestra m JOIN EL_KUELGUE.FABRICANTE f ON f.FABRICANTE_NOMBRE = m.FABRICANTE_NOMBRE 
WHERE[MODELO_CODIGO] IS NOT NULL
GO