INSERT INTO EL_KUELGUE.FACTURA
SELECT DISTINCT FACTURA_NRO, FACTURA_FECHA, PRECIO_FACTURADO, CLIENTE_CODIGO, SUCURSAL_CODIGO
FROM gd_esquema.Maestra m JOIN EL_KUELGUE.CLIENTE c ON (m.FAC_CLIENTE_APELLIDO = c.CLIENTE_APELLIDO AND m.FAC_CLIENTE_NOMBRE = c.CLIENTE_NOMBRE AND m.FAC_CLIENTE_DNI = c.CLIENTE_DNI)
                          JOIN EL_KUELGUE.SUCURSAL s ON (m.FAC_SUCURSAL_TELEFONO = s.SUCURSAL_TELEFONO)
WHERE FACTURA_NRO IS NOT NULL AND AUTO_PARTE_CODIGO IS NULL
UNION
SELECT DISTINCT FACTURA_NRO, FACTURA_FECHA, SUM(PRECIO_FACTURADO) PRECIO_FACTURADO, CLIENTE_CODIGO, SUCURSAL_CODIGO
FROM gd_esquema.Maestra m JOIN EL_KUELGUE.CLIENTE c ON (m.FAC_CLIENTE_APELLIDO = c.CLIENTE_APELLIDO AND m.FAC_CLIENTE_NOMBRE = c.CLIENTE_NOMBRE AND m.FAC_CLIENTE_DNI = c.CLIENTE_DNI)
                          JOIN EL_KUELGUE.SUCURSAL s ON (m.FAC_SUCURSAL_TELEFONO = s.SUCURSAL_TELEFONO)
WHERE COMPRA_NRO IS NULL AND FACTURA_NRO IS NOT NULL AND AUTO_PARTE_CODIGO IS NOT NULL
GROUP BY FACTURA_NRO, FACTURA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO
GO