USE [GD2C2020]
GO

--FUNCION AUX

IF OBJECT_ID ('EL_KUELGUE.OBTENER_MES', 'FN') IS NOT NULL  
   DROP FUNCTION EL_KUELGUE.OBTENER_MES; 
GO

CREATE FUNCTION EL_KUELGUE.OBTENER_MES (@MES INT)
RETURNS CHAR(12)
AS
BEGIN
	DECLARE @RETORNO_MES CHAR(12)
	
	SET @RETORNO_MES = CASE
				WHEN @MES = 1 THEN 'ENERO'
				WHEN @MES = 2 THEN 'FEBRERO'
				WHEN @MES = 3 THEN 'MARZO'
				WHEN @MES = 4 THEN 'ABRIL'
				WHEN @MES = 5 THEN 'MAYO'
				WHEN @MES = 6 THEN 'JUNIO'
				WHEN @MES = 7 THEN 'JULIO'
				WHEN @MES = 8 THEN 'AGOSTO'
				WHEN @MES = 9 THEN 'SEPTIEMBRE'
				WHEN @MES = 10 THEN 'OCTUBRE'
				WHEN @MES = 11 THEN 'NOVIEMBRE'
				WHEN @MES = 12 THEN 'DICIEMBRE'
	END
	RETURN @RETORNO_MES
END; 
GO

--DIMENSION FACTURA_FECHA

IF OBJECT_ID ('EL_KUELGUE.BI_FACTURA_FECHA', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_FACTURA_FECHA; 
GO

CREATE TABLE EL_KUELGUE.BI_FACTURA_FECHA (
	ID_FACTURA_FECHA DATETIME2(3) PRIMARY KEY,
	DIA INT,
	MES INT,
	ANIO INT)

INSERT INTO EL_KUELGUE.BI_FACTURA_FECHA (ID_FACTURA_FECHA, DIA, MES, ANIO)
SELECT FACTURA_FECHA, DATEPART(DAY, FACTURA_FECHA) DIA, DATEPART(MONTH, FACTURA_FECHA) MES, DATEPART(YEAR, FACTURA_FECHA) ANIO
FROM EL_KUELGUE.FACTURA
GROUP BY FACTURA_FECHA
ORDER BY DATEPART(DAY, FACTURA_FECHA), DATEPART(MONTH, FACTURA_FECHA), DATEPART(YEAR, FACTURA_FECHA)

--DIMENSION COMPRA_FECHA

IF OBJECT_ID ('EL_KUELGUE.BI_COMPRA_FECHA', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_COMPRA_FECHA; 
GO

CREATE TABLE EL_KUELGUE.BI_COMPRA_FECHA (
	ID_COMPRA_FECHA DATETIME2(3) PRIMARY KEY,
	DIA INT,
	MES INT,
	ANIO INT)

INSERT INTO EL_KUELGUE.BI_COMPRA_FECHA (ID_COMPRA_FECHA, DIA, MES, ANIO)
SELECT COMPRA_FECHA, DATEPART(DAY, COMPRA_FECHA) DIA, DATEPART(MONTH, COMPRA_FECHA) MES, DATEPART(YEAR, COMPRA_FECHA) ANIO
FROM EL_KUELGUE.COMPRA
GROUP BY COMPRA_FECHA
ORDER BY DATEPART(DAY, COMPRA_FECHA), DATEPART(MONTH, COMPRA_FECHA), DATEPART(YEAR, COMPRA_FECHA)

--DIMENSION CLIENTE 

IF OBJECT_ID ('EL_KUELGUE.BI_CLIENTE', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_CLIENTE; 
GO

CREATE TABLE EL_KUELGUE.BI_CLIENTE (
	CLIENTE_CODIGO		INT PRIMARY KEY,
	CLIENTE_NOMBRE		NVARCHAR(255),
	CLIENTE_APELLIDO	NVARCHAR(255),
	CLIENTE_DIRECCION	NVARCHAR(255),
	CLIENTE_DNI			DECIMAL(18,0),
	CLIENTE_FECHA_NAC	DATETIME2(3),
	CLIENTE_MAIL		NVARCHAR(255),
	CLIENTE_EDAD		INT)

INSERT INTO EL_KUELGUE.BI_CLIENTE
SELECT CLIENTE_CODIGO, CLIENTE_NOMBRE, CLIENTE_APELLIDO, CLIENTE_DIRECCION, CLIENTE_DNI, CLIENTE_FECHA_NAC, CLIENTE_MAIL, DATEDIFF(yy, CLIENTE_FECHA_NAC, GETDATE()) 
FROM EL_KUELGUE.CLIENTE
ORDER BY CLIENTE_CODIGO

--DIMENSION SUCURSAL

IF OBJECT_ID ('EL_KUELGUE.BI_SUCURSAL', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_SUCURSAL; 
GO

CREATE TABLE EL_KUELGUE.BI_SUCURSAL(
	SUCURSAL_CODIGO		INT PRIMARY KEY,
	SUCURSAL_DIRECCION	NVARCHAR(255),
	SUCURSAL_MAIL		NVARCHAR(255),
	SUCURSAL_TELEFONO	DECIMAL (18,0),
	SUCURSAL_CIUDAD 	NVARCHAR(255))

INSERT INTO EL_KUELGUE.BI_SUCURSAL
SELECT SUCURSAL_CODIGO,SUCURSAL_DIRECCION,SUCURSAL_MAIL,SUCURSAL_TELEFONO,SUCURSAL_CIUDAD
FROM EL_KUELGUE.SUCURSAL
ORDER BY SUCURSAL_CODIGO

-- DIMENSION FABRICANTE
IF OBJECT_ID ('EL_KUELGUE.BI_FABRICANTE', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_FABRICANTE; 
GO

CREATE TABLE EL_KUELGUE.BI_FABRICANTE (
    [FABRICANTE_CODIGO] INT PRIMARY KEY,
	[FABRICANTE_NOMBRE] [nvarchar](255) NOT NULL
)

INSERT INTO EL_KUELGUE.BI_FABRICANTE
SELECT FABRICANTE_CODIGO, FABRICANTE_NOMBRE
FROM EL_KUELGUE.FABRICANTE
ORDER BY FABRICANTE_NOMBRE
 
 -- DIMENSION MODELO
IF OBJECT_ID ('EL_KUELGUE.BI_MODELO', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_MODELO; 
GO

CREATE TABLE EL_KUELGUE.BI_MODELO (
    [MODELO_CODIGO] [decimal](18, 0) PRIMARY KEY,
    [MODELO_NOMBRE] [nvarchar](255) NOT NULL,
	[MODELO_POTENCIA] [decimal](18, 0) NOT NULL)

INSERT INTO EL_KUELGUE.BI_MODELO
SELECT MODELO_CODIGO, MODELO_NOMBRE, MODELO_POTENCIA
FROM EL_KUELGUE.MODELO
ORDER BY MODELO_CODIGO

-- DIMENSION TRANSMISION
IF OBJECT_ID ('EL_KUELGUE.BI_TRANSMISION', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_TRANSMISION; 
GO

CREATE TABLE EL_KUELGUE.BI_TRANSMISION (
    [TIPO_TRANSMISION_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[TIPO_TRANSMISION_DESC] [nvarchar](255) NOT NULL)

INSERT INTO EL_KUELGUE.BI_TRANSMISION
SELECT TIPO_TRANSMISION_CODIGO,TIPO_TRANSMISION_DESC 
FROM EL_KUELGUE.TRANSMISION
ORDER BY TIPO_TRANSMISION_CODIGO

-- DIMENSION CAJA
IF OBJECT_ID ('EL_KUELGUE.BI_CAJA', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_CAJA; 
GO

CREATE TABLE EL_KUELGUE.BI_CAJA (
    [TIPO_CAJA_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[TIPO_CAJA_DESC] [nvarchar](255) NOT NULL)

INSERT INTO EL_KUELGUE.BI_CAJA
SELECT TIPO_CAJA_CODIGO, TIPO_CAJA_DESC
FROM EL_KUELGUE.CAJA
ORDER BY TIPO_CAJA_CODIGO

-- DIMENSION MOTOR
IF OBJECT_ID ('EL_KUELGUE.BI_MOTOR', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_MOTOR; 
GO

CREATE TABLE EL_KUELGUE.BI_MOTOR (
    [TIPO_MOTOR_CODIGO] [decimal](18, 0) PRIMARY KEY)

INSERT INTO EL_KUELGUE.BI_MOTOR
SELECT TIPO_MOTOR_CODIGO
FROM EL_KUELGUE.MOTOR

-- DIMENSION TIPO_AUTOMOVIL
IF OBJECT_ID ('EL_KUELGUE.BI_TIPO_AUTOMOVIL', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_TIPO_AUTOMOVIL; 
GO

CREATE TABLE EL_KUELGUE.BI_TIPO_AUTOMOVIL (
    [TIPO_AUTO_CODIGO] [decimal](18, 0) PRIMARY KEY,
    [TIPO_AUTO_DESC] [nvarchar](255) NOT NULL)

INSERT INTO EL_KUELGUE.BI_TIPO_AUTOMOVIL
SELECT TIPO_AUTO_CODIGO, TIPO_AUTO_DESC
FROM EL_KUELGUE.TIPO_AUTOMOVIL
ORDER BY TIPO_AUTO_CODIGO

-- DIMENSION AUTOMOVIL
IF OBJECT_ID ('EL_KUELGUE.BI_AUTOMOVIL', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_AUTOMOVIL; 
GO

CREATE TABLE EL_KUELGUE.BI_AUTOMOVIL (
    [AUTO_CODIGO] INT PRIMARY KEY,
	[AUTO_PATENTE] [nvarchar](50) NOT NULL,
	[AUTO_NRO_MOTOR] [nvarchar](50) NOT NULL,
	[AUTO_NRO_CHASIS] [nvarchar](50) NOT NULL,
	[AUTO_FECHA_ALTA] [datetime2](3) NOT NULL,
	[AUTO_CANT_KMS] [decimal](18, 0) NOT NULL)

INSERT INTO EL_KUELGUE.BI_AUTOMOVIL
SELECT AUTO_CODIGO, AUTO_PATENTE, AUTO_NRO_MOTOR, AUTO_NRO_CHASIS, AUTO_FECHA_ALTA, AUTO_CANT_KMS
FROM EL_KUELGUE.AUTOMOVIL
ORDER BY AUTO_CODIGO

-- DIMENSION AUTO_PARTE
IF OBJECT_ID ('EL_KUELGUE.BI_AUTO_PARTE', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_AUTO_PARTE; 
GO

CREATE TABLE EL_KUELGUE.BI_AUTO_PARTE (
    [AUTO_PARTE_CODIGO] [decimal](18, 0) PRIMARY KEY,
	[AUTO_PARTE_DESC] [nvarchar](255) NOT NULL)

INSERT INTO EL_KUELGUE.BI_AUTO_PARTE
SELECT AUTO_PARTE_CODIGO, AUTO_PARTE_DESC
FROM EL_KUELGUE.AUTO_PARTE
ORDER BY AUTO_PARTE_CODIGO

-- HECHO COMPRAS_AUTOMOVILES
IF OBJECT_ID ('EL_KUELGUE.BI_COMPRAS_AUTOMOVILES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_COMPRAS_AUTOMOVILES; 
GO

CREATE TABLE EL_KUELGUE.BI_COMPRAS_AUTOMOVILES(
	[COMPRA_FECHA] [datetime2](3) NOT NULL,
	[CLIENTE_CODIGO] INT NOT NULL,
	[SUCURSAL_CODIGO] INT NOT NULL,
	[AUTO_CODIGO] INT NOT NULL,
	[TIPO_TRANSMISION_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_CAJA_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_MOTOR_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_AUTO_CODIGO] [decimal](18, 0) NOT NULL,
	[MODELO_CODIGO] [decimal](18, 0) NOT NULL,
	[FABRICANTE_CODIGO] [int] NOT NULL,
	[MONTO_COMPRADO] [decimal](18, 2) NOT NULL,

	PRIMARY KEY (COMPRA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, AUTO_CODIGO, 
				 TIPO_TRANSMISION_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO,
				 TIPO_AUTO_CODIGO, MODELO_CODIGO, FABRICANTE_CODIGO)
)

-- HECHO FACTURAS_AUTOMOVILES
IF OBJECT_ID ('EL_KUELGUE.BI_FACTURAS_AUTOMOVILES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_FACTURAS_AUTOMOVILES; 
GO

CREATE TABLE EL_KUELGUE.BI_FACTURAS_AUTOMOVILES(
	[FACTURA_FECHA] [datetime2](3) NOT NULL,
	[CLIENTE_CODIGO] INT NOT NULL,
	[SUCURSAL_CODIGO] INT NOT NULL,
	[AUTO_CODIGO] INT NOT NULL,
	[TIPO_TRANSMISION_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_CAJA_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_MOTOR_CODIGO] [decimal](18, 0) NOT NULL,
	[TIPO_AUTO_CODIGO] [decimal](18, 0) NOT NULL,
	[MODELO_CODIGO] [decimal](18, 0) NOT NULL,
	[FABRICANTE_CODIGO] [int] NOT NULL,
	[MONTO_FACTURADO] [decimal](18, 2) NOT NULL

	PRIMARY KEY (FACTURA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, AUTO_CODIGO, 
				 TIPO_TRANSMISION_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO,
				 TIPO_AUTO_CODIGO, MODELO_CODIGO, FABRICANTE_CODIGO)
)


-- HECHO COMPRAS_AUTO_PARTES
IF OBJECT_ID ('EL_KUELGUE.BI_COMPRAS_AUTO_PARTES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_COMPRAS_AUTO_PARTES; 
GO

CREATE TABLE EL_KUELGUE.BI_COMPRAS_AUTO_PARTES(
	[COMPRA_FECHA] [datetime2](3) NOT NULL,
	[CLIENTE_CODIGO] INT NOT NULL,
	[SUCURSAL_CODIGO] INT NOT NULL,
	[AUTO_PARTE_CODIGO] [decimal](18, 0) NOT NULL,
	[MODELO_CODIGO] [decimal](18, 0) NOT NULL,
	[FABRICANTE_CODIGO] [int] NOT NULL,
	[MONTO_COMPRADO] [decimal](18, 2) NOT NULL,
	[CANTIDAD_COMPRADA] INT NOT NULL

	PRIMARY KEY (COMPRA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, 
				 AUTO_PARTE_CODIGO, MODELO_CODIGO, FABRICANTE_CODIGO)
)

-- HECHO FACTURAS_AUTO_PARTES
IF OBJECT_ID ('EL_KUELGUE.BI_FACTURAS_AUTO_PARTES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_FACTURAS_AUTO_PARTES; 
GO

CREATE TABLE EL_KUELGUE.BI_FACTURAS_AUTO_PARTES(
	[FACTURA_FECHA] [datetime2](3) NOT NULL,
	[CLIENTE_CODIGO] INT NOT NULL,
	[SUCURSAL_CODIGO] INT NOT NULL,
	[AUTO_PARTE_CODIGO] [decimal](18, 0) NOT NULL,
	[MODELO_CODIGO] [decimal](18, 0) NOT NULL,
	[FABRICANTE_CODIGO] [int] NOT NULL,
	[MONTO_FACTURADO] [decimal](18, 2) NOT NULL,
	[CANTIDAD_FACTURADA] INT NOT NULL

	PRIMARY KEY (FACTURA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, 
				 AUTO_PARTE_CODIGO, MODELO_CODIGO, FABRICANTE_CODIGO)
)

-- CARGA COMPRAS_AUTOMOVILES
INSERT INTO EL_KUELGUE.BI_COMPRAS_AUTOMOVILES 
(COMPRA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, AUTO_CODIGO, 
TIPO_TRANSMISION_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, 
TIPO_AUTO_CODIGO, MODELO_CODIGO, FABRICANTE_CODIGO, MONTO_COMPRADO)
SELECT COMPRA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, CA.AUTO_CODIGO, 
	   TIPO_TRANSMISION_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, 
	   TIPO_AUTO_CODIGO, M.MODELO_CODIGO, FABRICANTE_CODIGO, COMPRA_PRECIO AS MONTO_COMPRADO
FROM EL_KUELGUE.COMPRA C JOIN EL_KUELGUE.COMPRA_AUTOMOVIL CA ON C.COMPRA_NRO = CA.COMPRA_NRO
						 JOIN EL_KUELGUE.AUTOMOVIL A ON CA.AUTO_CODIGO = A.AUTO_CODIGO
						 JOIN EL_KUELGUE.FICHA_TECNICA_AUTOMOVIL FTA ON A.FICHA_TECNICA_CODIGO = FTA.FICHA_TECNICA_CODIGO
						 JOIN EL_KUELGUE.MODELO M ON FTA.MODELO_CODIGO = M.MODELO_CODIGO

-- CARGA FACTURAS_AUTOMOVILES
INSERT INTO EL_KUELGUE.BI_FACTURAS_AUTOMOVILES 
(FACTURA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, AUTO_CODIGO, 
TIPO_TRANSMISION_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, 
TIPO_AUTO_CODIGO, MODELO_CODIGO, FABRICANTE_CODIGO, MONTO_FACTURADO)
SELECT FACTURA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, FA.AUTO_CODIGO, 
	   TIPO_TRANSMISION_CODIGO, TIPO_CAJA_CODIGO, TIPO_MOTOR_CODIGO, 
	   TIPO_AUTO_CODIGO, M.MODELO_CODIGO, FABRICANTE_CODIGO, FACTURA_PRECIO AS MONTO_FACTURADO
FROM EL_KUELGUE.FACTURA F JOIN EL_KUELGUE.FACTURA_AUTOMOVIL FA ON F.FACTURA_NRO = FA.FACTURA_NRO
						  JOIN EL_KUELGUE.AUTOMOVIL A ON FA.AUTO_CODIGO = A.AUTO_CODIGO
						  JOIN EL_KUELGUE.FICHA_TECNICA_AUTOMOVIL FTA ON A.FICHA_TECNICA_CODIGO = FTA.FICHA_TECNICA_CODIGO
						  JOIN EL_KUELGUE.MODELO M ON FTA.MODELO_CODIGO = M.MODELO_CODIGO

-- CARGA COMPRAS_AUTO_PARTES
INSERT INTO EL_KUELGUE.BI_COMPRAS_AUTO_PARTES
(COMPRA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, AUTO_PARTE_CODIGO,
MODELO_CODIGO, FABRICANTE_CODIGO, MONTO_COMPRADO, CANTIDAD_COMPRADA)
SELECT COMPRA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, CA.AUTO_PARTE_CODIGO, 
	   M.MODELO_CODIGO, FABRICANTE_CODIGO, SUM(COMPRA_PRECIO) MONTO_COMPRADO, SUM(COMPRA_CANT) CANTIDAD_COMPRADA
FROM EL_KUELGUE.COMPRA C JOIN EL_KUELGUE.DETALLE_COMPRA_AUTO_PARTE CA ON C.COMPRA_NRO = CA.COMPRA_NRO
						 JOIN EL_KUELGUE.AUTO_PARTE A ON CA.AUTO_PARTE_CODIGO = A.AUTO_PARTE_CODIGO
						 JOIN EL_KUELGUE.MODELO M ON A.MODELO_CODIGO = M.MODELO_CODIGO
GROUP BY COMPRA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, CA.AUTO_PARTE_CODIGO, M.MODELO_CODIGO, FABRICANTE_CODIGO

-- CARGA FACTURAS_AUTO_PARTES
INSERT INTO EL_KUELGUE.BI_FACTURAS_AUTO_PARTES
(FACTURA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, AUTO_PARTE_CODIGO,
MODELO_CODIGO, FABRICANTE_CODIGO, MONTO_FACTURADO, CANTIDAD_FACTURADA)
SELECT FACTURA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, FA.AUTO_PARTE_CODIGO, 
	   M.MODELO_CODIGO, FABRICANTE_CODIGO, SUM(FACTURA_PRECIO) MONTO_FACTURADO, SUM(FACTURA_CANT) CANTIDAD_FACTURADA
FROM EL_KUELGUE.FACTURA F JOIN EL_KUELGUE.DETALLE_FACTURA_AUTO_PARTE FA ON F.FACTURA_NRO = FA.FACTURA_NRO
						 JOIN EL_KUELGUE.AUTO_PARTE A ON FA.AUTO_PARTE_CODIGO = A.AUTO_PARTE_CODIGO
						 JOIN EL_KUELGUE.MODELO M ON A.MODELO_CODIGO = M.MODELO_CODIGO
GROUP BY FACTURA_FECHA, CLIENTE_CODIGO, SUCURSAL_CODIGO, FA.AUTO_PARTE_CODIGO, M.MODELO_CODIGO, FABRICANTE_CODIGO


-- ********** CREACION CONSTRAINS  **********

--FK BI_COMPRAS_AUTOMOVILES
ALTER TABLE EL_KUELGUE.BI_COMPRAS_AUTOMOVILES
ADD 
	FOREIGN KEY ([COMPRA_FECHA]) REFERENCES EL_KUELGUE.BI_COMPRA_FECHA([ID_COMPRA_FECHA]),
	FOREIGN KEY ([CLIENTE_CODIGO]) REFERENCES EL_KUELGUE.BI_CLIENTE([CLIENTE_CODIGO]),
	FOREIGN KEY ([SUCURSAL_CODIGO]) REFERENCES EL_KUELGUE.BI_SUCURSAL([SUCURSAL_CODIGO]),
	FOREIGN KEY ([AUTO_CODIGO]) REFERENCES EL_KUELGUE.BI_AUTOMOVIL([AUTO_CODIGO]),
	FOREIGN KEY ([TIPO_TRANSMISION_CODIGO]) REFERENCES EL_KUELGUE.BI_TRANSMISION([TIPO_TRANSMISION_CODIGO]),
	FOREIGN KEY ([TIPO_CAJA_CODIGO]) REFERENCES EL_KUELGUE.BI_CAJA([TIPO_CAJA_CODIGO]),
	FOREIGN KEY ([TIPO_MOTOR_CODIGO]) REFERENCES EL_KUELGUE.BI_MOTOR([TIPO_MOTOR_CODIGO]),
	FOREIGN KEY ([TIPO_AUTO_CODIGO]) REFERENCES EL_KUELGUE.BI_TIPO_AUTOMOVIL([TIPO_AUTO_CODIGO]),
	FOREIGN KEY ([MODELO_CODIGO]) REFERENCES EL_KUELGUE.BI_MODELO([MODELO_CODIGO]),
	FOREIGN KEY ([FABRICANTE_CODIGO]) REFERENCES EL_KUELGUE.BI_FABRICANTE([FABRICANTE_CODIGO]);
GO

--FK BI_FACTURAS_AUTOMOVILES
ALTER TABLE EL_KUELGUE.BI_FACTURAS_AUTOMOVILES
ADD 
	FOREIGN KEY ([FACTURA_FECHA]) REFERENCES EL_KUELGUE.BI_FACTURA_FECHA([ID_FACTURA_FECHA]),
	FOREIGN KEY ([CLIENTE_CODIGO]) REFERENCES EL_KUELGUE.BI_CLIENTE([CLIENTE_CODIGO]),
	FOREIGN KEY ([SUCURSAL_CODIGO]) REFERENCES EL_KUELGUE.BI_SUCURSAL([SUCURSAL_CODIGO]),
	FOREIGN KEY ([AUTO_CODIGO]) REFERENCES EL_KUELGUE.BI_AUTOMOVIL([AUTO_CODIGO]),
	FOREIGN KEY ([TIPO_TRANSMISION_CODIGO]) REFERENCES EL_KUELGUE.BI_TRANSMISION([TIPO_TRANSMISION_CODIGO]),
	FOREIGN KEY ([TIPO_CAJA_CODIGO]) REFERENCES EL_KUELGUE.BI_CAJA([TIPO_CAJA_CODIGO]),
	FOREIGN KEY ([TIPO_MOTOR_CODIGO]) REFERENCES EL_KUELGUE.BI_MOTOR([TIPO_MOTOR_CODIGO]),
	FOREIGN KEY ([TIPO_AUTO_CODIGO]) REFERENCES EL_KUELGUE.BI_TIPO_AUTOMOVIL([TIPO_AUTO_CODIGO]),
	FOREIGN KEY ([MODELO_CODIGO]) REFERENCES EL_KUELGUE.BI_MODELO([MODELO_CODIGO]),
	FOREIGN KEY ([FABRICANTE_CODIGO]) REFERENCES EL_KUELGUE.BI_FABRICANTE([FABRICANTE_CODIGO]);
GO

--FK BI_COMPRAS_AUTO_PARTES
ALTER TABLE EL_KUELGUE.BI_COMPRAS_AUTO_PARTES
ADD 
	FOREIGN KEY ([COMPRA_FECHA]) REFERENCES EL_KUELGUE.BI_COMPRA_FECHA([ID_COMPRA_FECHA]),
	FOREIGN KEY ([CLIENTE_CODIGO]) REFERENCES EL_KUELGUE.BI_CLIENTE([CLIENTE_CODIGO]),
	FOREIGN KEY ([SUCURSAL_CODIGO]) REFERENCES EL_KUELGUE.BI_SUCURSAL([SUCURSAL_CODIGO]),
	FOREIGN KEY ([AUTO_PARTE_CODIGO]) REFERENCES EL_KUELGUE.BI_AUTO_PARTE([AUTO_PARTE_CODIGO]),
	FOREIGN KEY ([MODELO_CODIGO]) REFERENCES EL_KUELGUE.BI_MODELO([MODELO_CODIGO]),
	FOREIGN KEY ([FABRICANTE_CODIGO]) REFERENCES EL_KUELGUE.BI_FABRICANTE([FABRICANTE_CODIGO]);
GO

--FK BI_FACTURAS_AUTO_PARTES
ALTER TABLE EL_KUELGUE.BI_FACTURAS_AUTO_PARTES
ADD 
	FOREIGN KEY ([FACTURA_FECHA]) REFERENCES EL_KUELGUE.BI_FACTURA_FECHA([ID_FACTURA_FECHA]),
	FOREIGN KEY ([CLIENTE_CODIGO]) REFERENCES EL_KUELGUE.BI_CLIENTE([CLIENTE_CODIGO]),
	FOREIGN KEY ([SUCURSAL_CODIGO]) REFERENCES EL_KUELGUE.BI_SUCURSAL([SUCURSAL_CODIGO]),
	FOREIGN KEY ([AUTO_PARTE_CODIGO]) REFERENCES EL_KUELGUE.BI_AUTO_PARTE([AUTO_PARTE_CODIGO]),
	FOREIGN KEY ([MODELO_CODIGO]) REFERENCES EL_KUELGUE.BI_MODELO([MODELO_CODIGO]),
	FOREIGN KEY ([FABRICANTE_CODIGO]) REFERENCES EL_KUELGUE.BI_FABRICANTE([FABRICANTE_CODIGO]);
GO

-- REQUERIMIENTOS FUNCIONALES --

------------------------------------------------------------------------------------------------------------------------------------
-- Cantidad de automóviles, vendidos y comprados x sucursal y mes

SELECT C1.SUCURSAL_CODIGO COMPRAS_SUCURSAL, F1.SUCURSAL_CODIGO FACTURAS_SUCURSAL, 
	   C1.MES COMPRAS_MES, C1.ANIO COMPRAS_ANIO, F1.MES FACTURAS_MES, F1.ANIO FACTURAS_ANIO, 
	   CANTIDADES_COMPRADAS, CANTIDADES_FACTURADAS, MONTO_COMPRADO, MONTO_FACTURADO
INTO #HISTORICO_COMPRAS_Y_VENTAS
FROM (SELECT F.SUCURSAL_CODIGO, SUM(MONTO_FACTURADO) MONTO_FACTURADO, COUNT(*) CANTIDADES_FACTURADAS, MES, ANIO
	  FROM EL_KUELGUE.BI_FACTURAS_AUTOMOVILES F JOIN EL_KUELGUE.BI_FACTURA_FECHA FECHA ON F.FACTURA_FECHA = FECHA.ID_FACTURA_FECHA
	  GROUP BY F.SUCURSAL_CODIGO, MES, ANIO) F1
	FULL OUTER JOIN 
	  (SELECT C.SUCURSAL_CODIGO, SUM(MONTO_COMPRADO) MONTO_COMPRADO, COUNT(*) CANTIDADES_COMPRADAS, MES, ANIO
	   FROM EL_KUELGUE.BI_COMPRAS_AUTOMOVILES C JOIN EL_KUELGUE.BI_COMPRA_FECHA FECHA ON C.COMPRA_FECHA = FECHA.ID_COMPRA_FECHA
	   GROUP BY C.SUCURSAL_CODIGO, MES, ANIO) C1
	ON (F1.SUCURSAL_CODIGO = C1.SUCURSAL_CODIGO AND F1.MES = C1.MES AND F1.ANIO = C1.ANIO)
ORDER BY C1.MES, F1.MES

IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES; 
GO

SELECT TOP 0 COMPRAS_SUCURSAL SUCURSAL, COMPRAS_MES MES, COMPRAS_ANIO ANIO, CANTIDADES_COMPRADAS CANTIDADES_COMPRADAS, 
			 CANTIDADES_FACTURADAS CANTIDADES_FACTURADAS, MONTO_COMPRADO, MONTO_FACTURADO
INTO EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES
FROM #HISTORICO_COMPRAS_Y_VENTAS

DECLARE @COMPRAS_SUCURSAL INT, @FACTURAS_SUCURSAL INT, 
		@COMPRAS_MES INT, @COMPRAS_ANIO INT, @FACTURAS_MES INT, @FACTURAS_ANIO INT, 
		@CANTIDADES_COMPRADAS INT, @CANTIDADES_FACTURADAS INT, @MONTO_COMPRADO BIGINT, @MONTO_FACTURADO BIGINT

DECLARE compras_y_ventas_cursor CURSOR FOR
SELECT COMPRAS_SUCURSAL, FACTURAS_SUCURSAL, COMPRAS_MES, COMPRAS_ANIO, FACTURAS_MES, FACTURAS_ANIO, 
	   CANTIDADES_COMPRADAS, CANTIDADES_FACTURADAS, MONTO_COMPRADO, MONTO_FACTURADO
FROM #HISTORICO_COMPRAS_Y_VENTAS

OPEN compras_y_ventas_cursor

FETCH NEXT FROM compras_y_ventas_cursor 
INTO @COMPRAS_SUCURSAL, @FACTURAS_SUCURSAL, @COMPRAS_MES, @COMPRAS_ANIO, @FACTURAS_MES, @FACTURAS_ANIO, 
	 @CANTIDADES_COMPRADAS, @CANTIDADES_FACTURADAS, @MONTO_COMPRADO, @MONTO_FACTURADO

WHILE(@@FETCH_STATUS = 0)
BEGIN
	IF @COMPRAS_SUCURSAL IS NULL AND @FACTURAS_SUCURSAL IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES (SUCURSAL, MES, ANIO, CANTIDADES_COMPRADAS, CANTIDADES_FACTURADAS, MONTO_COMPRADO, MONTO_FACTURADO)
		VALUES (@FACTURAS_SUCURSAL, @FACTURAS_MES, @FACTURAS_ANIO, 0, @CANTIDADES_FACTURADAS, 0, @MONTO_FACTURADO)
	END

	IF @FACTURAS_SUCURSAL IS NULL AND @COMPRAS_SUCURSAL IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES (SUCURSAL, MES, ANIO, CANTIDADES_COMPRADAS, CANTIDADES_FACTURADAS,MONTO_COMPRADO,MONTO_FACTURADO)
		VALUES (@COMPRAS_SUCURSAL, @COMPRAS_MES, @COMPRAS_ANIO, @CANTIDADES_COMPRADAS, 0, @MONTO_COMPRADO, 0)
	END

	IF @FACTURAS_SUCURSAL IS NOT NULL AND @COMPRAS_SUCURSAL IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES (SUCURSAL, MES, ANIO, CANTIDADES_COMPRADAS, CANTIDADES_FACTURADAS,MONTO_COMPRADO,MONTO_FACTURADO)
		VALUES (@COMPRAS_SUCURSAL, @COMPRAS_MES, @COMPRAS_ANIO, @CANTIDADES_COMPRADAS, @CANTIDADES_FACTURADAS, @MONTO_COMPRADO, @MONTO_FACTURADO)
	END

	FETCH NEXT FROM compras_y_ventas_cursor 
	INTO @COMPRAS_SUCURSAL, @FACTURAS_SUCURSAL, @COMPRAS_MES, @COMPRAS_ANIO, @FACTURAS_MES, @FACTURAS_ANIO, 
		 @CANTIDADES_COMPRADAS, @CANTIDADES_FACTURADAS,@MONTO_COMPRADO,@MONTO_FACTURADO
END

CLOSE compras_y_ventas_cursor
DEALLOCATE compras_y_ventas_cursor

DROP TABLE #HISTORICO_COMPRAS_Y_VENTAS

GO
IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES_V', 'V') IS NOT NULL  
   DROP VIEW EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES_V; 
GO

CREATE VIEW EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES_V
(SUCURSAL, CANTIDADES_COMPRADAS, CANTIDADES_FACTURADAS, MES, ANIO)
AS
SELECT SUCURSAL, CANTIDADES_COMPRADAS, CANTIDADES_FACTURADAS, MES, ANIO
FROM EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES
GO

SELECT SUCURSAL, CANTIDADES_COMPRADAS, CANTIDADES_FACTURADAS, EL_KUELGUE.OBTENER_MES(MES) MES, ANIO
FROM EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES_V
--ORDER BY SUCURSAL, ANIO, MES

IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_BALANCES_AUTOMOVILES_V', 'V') IS NOT NULL  
   DROP VIEW EL_KUELGUE.BI_REPORTE_BALANCES_AUTOMOVILES_V; 
GO

CREATE VIEW EL_KUELGUE.BI_REPORTE_BALANCES_AUTOMOVILES_V
(SUCURSAL, MONTO_COMPRADO, MONTO_FACTURADO, BALANCE, MES, ANIO)
AS
SELECT SUCURSAL, MONTO_COMPRADO, MONTO_FACTURADO, (MONTO_FACTURADO - MONTO_COMPRADO) BALANCE, MES, ANIO
FROM EL_KUELGUE.BI_REPORTE_CANTIDADES_AUTOMOVILES
GO

SELECT SUCURSAL, MONTO_COMPRADO, MONTO_FACTURADO, BALANCE, EL_KUELGUE.OBTENER_MES(MES) MES, ANIO
FROM EL_KUELGUE.BI_REPORTE_BALANCES_AUTOMOVILES_V
ORDER BY SUCURSAL, ANIO, MES

---------------------------------------------------------------------------------------
-- Precio promedio de automóviles, vendidos y comprados.

SELECT ca.MODELO_CODIGO, COUNT(ca.MODELO_CODIGO) CANTIDAD_VENDIDOS, SUM(MONTO_FACTURADO) / COUNT(ca.MODELO_CODIGO) PRECIO_PROMEDIO_VENTAS
INTO #PRECIO_PROMEDIO_X_VENTAS
FROM EL_KUELGUE.BI_COMPRAS_AUTOMOVILES ca
JOIN EL_KUELGUE.BI_FACTURAS_AUTOMOVILES fa on ca.AUTO_CODIGO = fa.AUTO_CODIGO
GROUP BY ca.MODELO_CODIGO
ORDER BY CANTIDAD_VENDIDOS

SELECT ca.MODELO_CODIGO, COUNT(ca.MODELO_CODIGO) CANTIDAD_COMPRADOS, SUM(MONTO_COMPRADO) / COUNT(ca.MODELO_CODIGO) PRECIO_PROMEDIO_COMPRAS
INTO #PRECIO_PROMEDIO_X_COMPRAS
FROM EL_KUELGUE.BI_COMPRAS_AUTOMOVILES ca
JOIN EL_KUELGUE.BI_FACTURAS_AUTOMOVILES fa on ca.AUTO_CODIGO = fa.AUTO_CODIGO
GROUP BY ca.MODELO_CODIGO
ORDER BY CANTIDAD_COMPRADOS

IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_PRECIO_PROMEDIO_AUTOMOVILES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_REPORTE_PRECIO_PROMEDIO_AUTOMOVILES; 
GO

SELECT ca.MODELO_CODIGO, CANTIDAD_COMPRADOS, PRECIO_PROMEDIO_COMPRAS, CANTIDAD_VENDIDOS, PRECIO_PROMEDIO_VENTAS
INTO EL_KUELGUE.BI_REPORTE_PRECIO_PROMEDIO_AUTOMOVILES
FROM #PRECIO_PROMEDIO_X_COMPRAS ca JOIN #PRECIO_PROMEDIO_X_VENTAS v ON ca.MODELO_CODIGO = V.MODELO_CODIGO

IF OBJECT_ID ('EL_KUELGUE.BI_PRECIO_PROMEDIO_AUTOMOVILES_V', 'V') IS NOT NULL  
   DROP VIEW EL_KUELGUE.BI_PRECIO_PROMEDIO_AUTOMOVILES_V; 
GO

CREATE VIEW EL_KUELGUE.BI_PRECIO_PROMEDIO_AUTOMOVILES_V
AS
SELECT MODELO_CODIGO, CANTIDAD_COMPRADOS, PRECIO_PROMEDIO_COMPRAS, CANTIDAD_VENDIDOS, PRECIO_PROMEDIO_VENTAS
FROM EL_KUELGUE.BI_REPORTE_PRECIO_PROMEDIO_AUTOMOVILES
GO

DROP TABLE #PRECIO_PROMEDIO_X_COMPRAS
DROP TABLE #PRECIO_PROMEDIO_X_VENTAS

------------------------------------------------------------------------------------------------------------------------------------
-- Promedio de tiempo en stock de cada modelo de automóvil

SELECT MODELO_CODIGO, AVG(DATEDIFF(dd, COMPRA_FECHA, FACTURA_FECHA)) PROMEDIODIAS
INTO #PROMEDIO_STOCK_AUTO
FROM (SELECT ca.MODELO_CODIGO, COMPRA_FECHA, COALESCE(FACTURA_FECHA, GETDATE()) FACTURA_FECHA
	  FROM EL_KUELGUE.BI_COMPRAS_AUTOMOVILES ca 
	  JOIN EL_KUELGUE.BI_FACTURAS_AUTOMOVILES fa ON ca.AUTO_CODIGO = fa.AUTO_CODIGO) A
GROUP BY MODELO_CODIGO
ORDER BY PROMEDIODIAS

IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_PROMEDIO_TIEMPO_EN_STOCK_CADA_AUTOMOVIL', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_REPORTE_PROMEDIO_TIEMPO_EN_STOCK_CADA_AUTOMOVIL
GO

SELECT MODELO_CODIGO, PROMEDIODIAS
INTO EL_KUELGUE.BI_REPORTE_PROMEDIO_TIEMPO_EN_STOCK_CADA_AUTOMOVIL
FROM #PROMEDIO_STOCK_AUTO
ORDER BY PROMEDIODIAS

IF OBJECT_ID ('EL_KUELGUE.BI_PROMEDIO_TIEMPO_EN_STOCK_CADA_AUTOMOVIL_V', 'V') IS NOT NULL  
   DROP VIEW EL_KUELGUE.BI_PROMEDIO_TIEMPO_EN_STOCK_CADA_AUTOMOVIL_V; 
GO

CREATE VIEW EL_KUELGUE.BI_PROMEDIO_TIEMPO_EN_STOCK_CADA_AUTOMOVIL_V
AS
SELECT MODELO_CODIGO, PROMEDIODIAS
FROM EL_KUELGUE.BI_REPORTE_PROMEDIO_TIEMPO_EN_STOCK_CADA_AUTOMOVIL
GO

DROP TABLE #PROMEDIO_STOCK_AUTO

--------------------------------------------------------------------------------------
-- Precio promedio de autopartes, vendidos y comprados.

SELECT ca.AUTO_PARTE_CODIGO, ca.MODELO_CODIGO, COUNT(fa.MODELO_CODIGO) CANTIDAD_VENDIDOS,
	   SUM(MONTO_FACTURADO) / COUNT(fa.MODELO_CODIGO) PRECIO_PROMEDIO_VENTAS
INTO #PRECIO_PROMEDIO_X_VENTAS
FROM EL_KUELGUE.BI_COMPRAS_AUTO_PARTES ca
JOIN EL_KUELGUE.BI_FACTURAS_AUTO_PARTES fa ON ca.AUTO_PARTE_CODIGO = fa.AUTO_PARTE_CODIGO
GROUP BY ca.AUTO_PARTE_CODIGO, ca.MODELO_CODIGO
ORDER BY CANTIDAD_VENDIDOS


SELECT ca.AUTO_PARTE_CODIGO,  ca.MODELO_CODIGO, COUNT(ca.MODELO_CODIGO) CANTIDAD_COMPRADOS, 
	   SUM(MONTO_COMPRADO) / COUNT(ca.MODELO_CODIGO) PRECIO_PROMEDIO_COMPRAS
INTO #PRECIO_PROMEDIO_X_COMPRAS
FROM EL_KUELGUE.BI_COMPRAS_AUTO_PARTES ca
JOIN EL_KUELGUE.BI_FACTURAS_AUTO_PARTES fa ON ca.AUTO_PARTE_CODIGO = fa.AUTO_PARTE_CODIGO
GROUP BY ca.AUTO_PARTE_CODIGO, ca.MODELO_CODIGO
ORDER BY CANTIDAD_COMPRADOS

IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_PRECIO_PROMEDIO_AUTO_PARTES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_REPORTE_PRECIO_PROMEDIO_AUTO_PARTES; 
GO

SELECT c.AUTO_PARTE_CODIGO, c.MODELO_CODIGO, CANTIDAD_COMPRADOS, PRECIO_PROMEDIO_COMPRAS, CANTIDAD_VENDIDOS, PRECIO_PROMEDIO_VENTAS
INTO EL_KUELGUE.BI_REPORTE_PRECIO_PROMEDIO_AUTO_PARTES
FROM #PRECIO_PROMEDIO_X_COMPRAS c 
JOIN #PRECIO_PROMEDIO_X_VENTAS v ON C.AUTO_PARTE_CODIGO = V.AUTO_PARTE_CODIGO

IF OBJECT_ID ('EL_KUELGUE.BI_PRECIO_PROMEDIO_AUTO_PARTES_V', 'V') IS NOT NULL  
   DROP VIEW EL_KUELGUE.BI_PRECIO_PROMEDIO_AUTO_PARTES_V; 
GO

CREATE VIEW EL_KUELGUE.BI_PRECIO_PROMEDIO_AUTO_PARTES_V
AS
SELECT AUTO_PARTE_CODIGO, MODELO_CODIGO, CANTIDAD_COMPRADOS, PRECIO_PROMEDIO_COMPRAS, CANTIDAD_VENDIDOS, PRECIO_PROMEDIO_VENTAS
FROM EL_KUELGUE.BI_REPORTE_PRECIO_PROMEDIO_AUTO_PARTES
GO

DROP TABLE #PRECIO_PROMEDIO_X_COMPRAS
DROP TABLE #PRECIO_PROMEDIO_X_VENTAS

-- Ganancias de automoviles,  x sucursal y mes
SELECT SUCURSAL_CODIGO,
	   MONTO_FACTURADO TOTAL_FACTURADO,
	   AUTO_CODIGO,
	   MONTH(FACTURA_FECHA) MES,
	   YEAR(FACTURA_FECHA) ANIO
INTO #HISTORICO_FACTURAS_AUTOMOVILES_GANANCIAS
FROM EL_KUELGUE.BI_FACTURAS_AUTOMOVILES
ORDER BY SUCURSAL_CODIGO, ANIO, MES ASC

SELECT SUCURSAL_CODIGO, 
	   MONTO_COMPRADO TOTAL_COMPRADO,
	   AUTO_CODIGO,
	   MONTH(COMPRA_FECHA) MES, 
	   YEAR(COMPRA_FECHA) ANIO 
INTO #HISTORICO_COMPRAS_AUTOMOVILES_GANANCIAS
FROM EL_KUELGUE.BI_COMPRAS_AUTOMOVILES
ORDER BY SUCURSAL_CODIGO, ANIO, MES ASC

SELECT c.SUCURSAL_CODIGO compras_sucursal, f.SUCURSAL_CODIGO facturas_sucursal, c.MES compras_mes, c.ANIO compras_anio, f.MES facturas_mes, f.ANIO facturas_anio,f.AUTO_CODIGO factura_auto_codigo,c.AUTO_CODIGO compra_auto_codigo,f.TOTAL_FACTURADO,c.TOTAL_COMPRADO
INTO #HISTORICO_COMPRAS_Y_VENTAS_GANANCIAS
FROM #HISTORICO_FACTURAS_AUTOMOVILES_GANANCIAS f FULL OUTER JOIN #HISTORICO_COMPRAS_AUTOMOVILES_GANANCIAS C
ON (f.sucursal_codigo = c.sucursal_codigo AND f.AUTO_CODIGO = c.AUTO_CODIGO)
ORDER BY c.mes, f.mes


IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES; 
GO

SELECT TOP 0 compras_sucursal sucursal, compras_mes mes, compras_anio anio,(TOTAL_FACTURADO-TOTAL_COMPRADO)ganancias 
INTO EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES
FROM #HISTORICO_COMPRAS_Y_VENTAS_GANANCIAS

DECLARE @compras_sucursal INT, @facturas_sucursal INT, @compras_mes INT, @compras_anio INT, @facturas_mes INT, @facturas_anio INT,@TOTAL_COMPRADO INT,@TOTAL_FACTURADO INT

DECLARE compras_y_ventas_cursor CURSOR FOR
SELECT compras_sucursal, facturas_sucursal, compras_mes, compras_anio, facturas_mes, facturas_anio,TOTAL_COMPRADO ,TOTAL_FACTURADO
FROM #HISTORICO_COMPRAS_Y_VENTAS_GANANCIAS

OPEN compras_y_ventas_cursor

FETCH NEXT FROM compras_y_ventas_cursor INTO @compras_sucursal, @facturas_sucursal, @compras_mes, @compras_anio, @facturas_mes, @facturas_anio, @TOTAL_COMPRADO ,@TOTAL_FACTURADO

WHILE(@@FETCH_STATUS = 0)
BEGIN
	IF @compras_sucursal IS NULL AND @facturas_sucursal IS NOT NULL --Como calcular la ganancia si no hubo una compra del auto
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES (sucursal, mes, anio, ganancias)
		VALUES (@facturas_sucursal, @facturas_mes, @facturas_anio,@TOTAL_FACTURADO )
	END

	IF @facturas_sucursal IS NULL AND @compras_sucursal IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES (sucursal, mes, anio, ganancias)
		VALUES (@compras_sucursal, @compras_mes, @compras_anio, 0)
	END

	IF @facturas_sucursal IS NOT NULL AND @compras_sucursal IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES (sucursal, mes, anio, ganancias)
		VALUES (@compras_sucursal, @compras_mes, @compras_anio, (@TOTAL_FACTURADO-@TOTAL_COMPRADO))
	END

	FETCH NEXT FROM compras_y_ventas_cursor INTO @compras_sucursal, @facturas_sucursal, @compras_mes, @compras_anio, @facturas_mes, @facturas_anio, @TOTAL_COMPRADO ,@TOTAL_FACTURADO
END

CLOSE compras_y_ventas_cursor
DEALLOCATE compras_y_ventas_cursor

DROP TABLE #HISTORICO_COMPRAS_AUTOMOVILES_GANANCIAS
DROP TABLE #HISTORICO_FACTURAS_AUTOMOVILES_GANANCIAS
DROP TABLE #HISTORICO_COMPRAS_Y_VENTAS_GANANCIAS

GO
IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES_V', 'V') IS NOT NULL  
   DROP VIEW EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES_V; 
GO

CREATE VIEW EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES_V(SUCURSAL,GANANCIAS, MES, ANIO)
AS
SELECT sucursal, SUM(ganancias), mes, anio
FROM EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES
GROUP BY sucursal,mes,anio
GO

SELECT SUCURSAL, GANANCIAS, MES, ANIO
FROM EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOMOVILES_V
ORDER BY SUCURSAL, ANIO, MES

-- Ganancias de autopartes,  x sucursal y mes
SELECT SUCURSAL_CODIGO,
	   MONTO_FACTURADO TOTAL_FACTURADO,
	   AUTO_PARTE_CODIGO,
	   MONTH(FACTURA_FECHA) MES,
	   YEAR(FACTURA_FECHA) ANIO
INTO #HISTORICO_FACTURAS_AUTOPARTES_GANANCIAS
FROM EL_KUELGUE.BI_FACTURAS_AUTO_PARTES
ORDER BY SUCURSAL_CODIGO, ANIO, MES ASC

SELECT SUCURSAL_CODIGO, 
	   MONTO_COMPRADO TOTAL_COMPRADO,
	   AUTO_PARTE_CODIGO,
	   MONTH(COMPRA_FECHA) MES, 
	   YEAR(COMPRA_FECHA) ANIO 
INTO #HISTORICO_COMPRAS_AUTOPARTES_GANANCIAS
FROM EL_KUELGUE.BI_COMPRAS_AUTO_PARTES
ORDER BY SUCURSAL_CODIGO, ANIO, MES ASC

SELECT c.sucursal_codigo compras_sucursal, f.sucursal_codigo facturas_sucursal, c.mes compras_mes, c.anio compras_anio, f.mes facturas_mes, f.anio facturas_anio,f.AUTO_PARTE_CODIGO factura_autoparte_codigo,c.AUTO_PARTE_CODIGO compra_autoparte_codigo,f.TOTAL_FACTURADO,c.TOTAL_COMPRADO
INTO #HISTORICO_COMPRAS_Y_VENTAS_AUTOPARTES_GANANCIAS
FROM #HISTORICO_FACTURAS_AUTOPARTES_GANANCIAS f FULL OUTER JOIN #HISTORICO_COMPRAS_AUTOPARTES_GANANCIAS C
ON (f.sucursal_codigo = c.sucursal_codigo AND f.AUTO_PARTE_CODIGO = c.AUTO_PARTE_CODIGO)
ORDER BY c.mes, f.mes

IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES; 
GO

SELECT TOP 0 compras_sucursal sucursal, compras_mes mes, compras_anio anio,(TOTAL_FACTURADO-TOTAL_COMPRADO)ganancias
INTO EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES
FROM #HISTORICO_COMPRAS_Y_VENTAS_AUTOPARTES_GANANCIAS

DECLARE @compras_sucursal INT, @facturas_sucursal INT, @compras_mes INT, @compras_anio INT, @facturas_mes INT, @facturas_anio INT, @TOTAL_COMPRADO INT,@TOTAL_FACTURADO INT

DECLARE compras_y_ventas_cursor CURSOR FOR
SELECT compras_sucursal, facturas_sucursal, compras_mes, compras_anio, facturas_mes, facturas_anio,TOTAL_COMPRADO,TOTAL_FACTURADO
FROM #HISTORICO_COMPRAS_Y_VENTAS_AUTOPARTES_GANANCIAS

OPEN compras_y_ventas_cursor

FETCH NEXT FROM compras_y_ventas_cursor INTO @compras_sucursal, @facturas_sucursal, @compras_mes, @compras_anio, @facturas_mes, @facturas_anio,@TOTAL_COMPRADO,@TOTAL_FACTURADO

WHILE(@@FETCH_STATUS = 0)
BEGIN
	IF @compras_sucursal IS NULL AND @facturas_sucursal IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES (sucursal, mes, anio, ganancias)
		VALUES (@facturas_sucursal, @facturas_mes, @facturas_anio,@TOTAL_FACTURADO)
	END

	IF @facturas_sucursal IS NULL AND @compras_sucursal IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES(sucursal, mes, anio, ganancias)
		VALUES (@compras_sucursal, @compras_mes, @compras_anio, 0)
	END

	IF @facturas_sucursal IS NOT NULL AND @compras_sucursal IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES (sucursal, mes, anio, ganancias)
		VALUES (@compras_sucursal, @compras_mes, @compras_anio, @TOTAL_FACTURADO)
	END

	FETCH NEXT FROM compras_y_ventas_cursor INTO @compras_sucursal, @facturas_sucursal, @compras_mes, @compras_anio, @facturas_mes, @facturas_anio,@TOTAL_COMPRADO,@TOTAL_FACTURADO
END

CLOSE compras_y_ventas_cursor
DEALLOCATE compras_y_ventas_cursor

DROP TABLE #HISTORICO_COMPRAS_AUTOPARTES_GANANCIAS
DROP TABLE #HISTORICO_FACTURAS_AUTOPARTES_GANANCIAS
DROP TABLE #HISTORICO_COMPRAS_Y_VENTAS_AUTOPARTES_GANANCIAS

GO
IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES_V', 'V') IS NOT NULL  
   DROP VIEW EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES_V; 
GO

CREATE VIEW EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES_V(SUCURSAL, GANANCIAS, MES, ANIO)
AS
SELECT sucursal,SUM(ganancias),mes, anio
FROM EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES
GROUP BY sucursal,mes,anio
GO

SELECT sucursal, ganancias,EL_KUELGUE.OBTENER_MES(mes)mes, anio
FROM EL_KUELGUE.BI_REPORTE_GANANCIAS_AUTOPARTES_V
ORDER BY sucursal, ANIO, MES

-- Maxima cantidad de stock de autopartes por cada sucursal(anual)
SELECT SUCURSAL_CODIGO,
	   COUNT(CANTIDAD_FACTURADA) CANTIDADES_VENDIDAS,
	   AUTO_PARTE_CODIGO,
	   MONTH(FACTURA_FECHA) MES,
	   YEAR(FACTURA_FECHA) ANIO
INTO #HISTORICO_FACTURAS_AUTOPARTES_MAXIMO
FROM EL_KUELGUE.BI_FACTURAS_AUTO_PARTES 
GROUP BY SUCURSAL_CODIGO,MONTH(FACTURA_FECHA),YEAR(FACTURA_FECHA), AUTO_PARTE_CODIGO
ORDER BY SUCURSAL_CODIGO, ANIO, MES ASC

SELECT SUCURSAL_CODIGO, 
	   COUNT(CANTIDAD_COMPRADA) CANTIDADES_COMPRADAS,
	   AUTO_PARTE_CODIGO,
	   MONTH(COMPRA_FECHA) MES, 
	   YEAR(COMPRA_FECHA) ANIO 
INTO #HISTORICO_COMPRAS_AUTOPARTES_MAXIMO
FROM EL_KUELGUE.BI_COMPRAS_AUTO_PARTES
GROUP BY SUCURSAL_CODIGO, MONTH(COMPRA_FECHA), YEAR(COMPRA_FECHA),AUTO_PARTE_CODIGO
ORDER BY SUCURSAL_CODIGO, ANIO, MES ASC

SELECT c.sucursal_codigo compras_sucursal, f.sucursal_codigo facturas_sucursal, c.mes compras_mes, c.anio compras_anio, f.mes facturas_mes, f.anio facturas_anio, CANTIDADES_COMPRADAS, CANTIDADES_VENDIDAS,f.AUTO_PARTE_CODIGO factura_autoparte_codigo,c.AUTO_PARTE_CODIGO compra_autoparte_codigo
INTO #HISTORICO_COMPRAS_Y_VENTAS_AUTOPARTES_MAXIMO
FROM #HISTORICO_FACTURAS_AUTOPARTES_MAXIMO f FULL OUTER JOIN #HISTORICO_COMPRAS_AUTOPARTES_MAXIMO C
ON (f.sucursal_codigo = c.sucursal_codigo AND f.AUTO_PARTE_CODIGO = c.AUTO_PARTE_CODIGO)
ORDER BY compras_sucursal, facturas_sucursal,c.ANIO, f.ANIO,c.MES, f.MES

IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES; 
GO

SELECT TOP 0 compras_sucursal sucursal, compras_mes mes, compras_anio anio, (CANTIDADES_COMPRADAS- CANTIDADES_VENDIDAS) stock
INTO EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES
FROM #HISTORICO_COMPRAS_Y_VENTAS_AUTOPARTES_MAXIMO

DECLARE @compras_sucursal INT, @facturas_sucursal INT, @compras_mes INT, @compras_anio INT, @facturas_mes INT, @facturas_anio INT, @CANTIDADES_COMPRADAS INT, @CANTIDADES_VENDIDAS INT

DECLARE compras_y_ventas_cursor CURSOR FOR
SELECT compras_sucursal, facturas_sucursal, compras_mes, compras_anio, facturas_mes, facturas_anio, CANTIDADES_COMPRADAS, CANTIDADES_VENDIDAS
FROM #HISTORICO_COMPRAS_Y_VENTAS_AUTOPARTES_MAXIMO

OPEN compras_y_ventas_cursor

FETCH NEXT FROM compras_y_ventas_cursor INTO @compras_sucursal, @facturas_sucursal, @compras_mes, @compras_anio, @facturas_mes, @facturas_anio, @CANTIDADES_COMPRADAS, @CANTIDADES_VENDIDAS

WHILE(@@FETCH_STATUS = 0)
BEGIN
	IF @compras_sucursal IS NULL AND @facturas_sucursal IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES (sucursal, mes, anio, stock)
		VALUES (@facturas_sucursal, @facturas_mes, @facturas_anio,-@CANTIDADES_VENDIDAS)
	END

	IF @facturas_sucursal IS NULL AND @compras_sucursal IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES (sucursal, mes, anio, stock)
		VALUES (@compras_sucursal, @compras_mes, @compras_anio, @CANTIDADES_COMPRADAS)
	END

	IF @facturas_sucursal IS NOT NULL AND @compras_sucursal IS NOT NULL
	BEGIN
		INSERT INTO EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES (sucursal, mes, anio, stock)
		VALUES (@compras_sucursal, @compras_mes, @compras_anio, @CANTIDADES_COMPRADAS-@CANTIDADES_VENDIDAS)
	END

	FETCH NEXT FROM compras_y_ventas_cursor INTO @compras_sucursal, @facturas_sucursal, @compras_mes, @compras_anio, @facturas_mes, @facturas_anio, @CANTIDADES_COMPRADAS, @CANTIDADES_VENDIDAS
END

CLOSE compras_y_ventas_cursor
DEALLOCATE compras_y_ventas_cursor

DROP TABLE #HISTORICO_COMPRAS_AUTOPARTES_MAXIMO
DROP TABLE #HISTORICO_FACTURAS_AUTOPARTES_MAXIMO
DROP TABLE #HISTORICO_COMPRAS_Y_VENTAS_AUTOPARTES_MAXIMO

GO

SELECT sucursal,SUM(stock) stock,mes, anio
INTO #stock
FROM EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES
GROUP BY sucursal,mes,anio


IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_FINAL', 'U') IS NOT NULL  
   DROP TABLE EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_FINAL; 
GO

SELECT TOP 0  sucursal,  mes,  anio, stock
INTO EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_FINAL
FROM #stock

DECLARE @sucursal INT,@sucursal_actual INT, @mes INT, @anio INT,@stock INT,@stock_inicial INT
DECLARE compras_y_ventas_cursor CURSOR FOR

SELECT sucursal,stock,mes,anio
FROM #stock
ORDER BY sucursal,anio,mes

OPEN compras_y_ventas_cursor

FETCH NEXT FROM compras_y_ventas_cursor INTO @sucursal,@stock, @mes, @anio
SET @sucursal_actual=@sucursal
WHILE(@@FETCH_STATUS = 0)
BEGIN
	IF(@sucursal_actual!=@sucursal)
		SET @sucursal_actual=@sucursal
	IF  @mes = 1 AND @anio = 2018
		BEGIN
			SET @stock_inicial = @stock
			INSERT INTO EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_FINAL (sucursal, mes, anio, stock)
			VALUES (@sucursal, @mes, @anio,@stock)
		END
	ELSE
	BEGIN
		SET @stock_inicial = @stock_inicial+ @stock
		INSERT INTO EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_FINAL (sucursal, mes, anio, stock)
		VALUES (@sucursal, @mes, @anio,@stock_inicial)
	END
	FETCH NEXT FROM compras_y_ventas_cursor INTO @sucursal,@stock, @mes, @anio
END
CLOSE compras_y_ventas_cursor
DEALLOCATE compras_y_ventas_cursor

DROP TABLE #stock

IF OBJECT_ID ('EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_V', 'V') IS NOT NULL  
   DROP VIEW EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_V; 
GO

CREATE VIEW EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_V(sucursal,stock, anio)
AS
SELECT sucursal,MAX(stock)maximo_stock,anio
FROM EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_FINAL
GROUP BY sucursal,anio
GO

SELECT sucursal,stock,anio
FROM EL_KUELGUE.BI_REPORTE_MAXIMO_AUTOPARTES_V
ORDER BY SUCURSAL,ANIO

